
services:
  server:
    build:
      context: .
    ports:
      - 9000:80

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./your-app.sql:/docker-entrypoint-initdb.d/your-app.sql
    ports:
      - "3306:3306"

volumes:
  db_data: